### PR TITLE
Translation cj

### PR DESCRIPTION
**Pull request by nutnutwin**
hi, just did the Simplified Chinese translation

### CODE REVIEW

**Comment by nutnutwin** [comment]
@ransome1 
Hi, from
https://github.com/ransome1/sleek/issues/141
I did a Simplified Chinese Translation

- to avoid Garbled Characters I used UTF-8
- This is Simplified Chinese so it might be better to have sc/translation.json
- in case someone want to do a tc/translation.json(For Traditional Chinese)
- if there are any problem please let me know, will send you by mail
- I dont know how to compile, so I cannot verify all the translations. Will Proofread in real software on next merge/release
Thank you

**Comment by ransome1** [comment]
Thanks a lot, thi sis really great.

Please give me some time to check this. Right now I'm working on another enhancement and to make Simpilfied Chinese available in sleek might be connected with replacing the font. As soon as I have a clear picture on the tasks that will result of this, I'll get back to you.

**Comment by nutnutwin** [comment]
Sure no need to hurry
will work on the jp later(no native speaker though)
imho it is preferrable to use CJK generic font(best to be fixed width) like noto by Google, or just make it customizable
just a thought

**Comment by ransome1** [comment]
@nutnutwin, what would be the proper dropdown entry for SC? Right now all languages are written out in their own language. I suppose we should do the same with SC.
image

**Comment by nutnutwin** [comment]
@ransome1 Hi 
简体中文
should be OK

**Pull request merged**
