### PR TITLE
Recurrences

### PR DESCRIPTION
**Pull request by zerodat**
This PR addresses #85 by providing the "b" business days unit for recurrences and the UI features for the recurrence picker, etc.  This probably should close the issue, but note that it doesn't provide any options to change what days of the week are business days -- in this implementation, Mon-Fri are business days and Sat/Sun are not.  I believe that this is consistent with other todo.txt tools that support business days (like topydo).

A note for @Moonbase59: you mentioned the syntax "rec:+2b" which is understood by todo.txt tools such as topydo and simpletask.  I have written some code to implement this choice between "strict" recurrence (relative) and "non-strict" recurrence (absolute) in sleek, but it won't work until we get an upstream fix to jsTodoTxt that will support the use of the plus in a rec value.  Right now with the existing jsTodoTxt, if you have a "+" in a recurrence (like rec:+2b) and there is also a project tag (like, +Manhattan) then the jsTodoTxt library will strip out the recurrence value leaving just "rec:".  This is also the cause of #128. I've submitted a PR to jsTodoTxt to fix this.  Once we have that fix, I will propose my change to support the +2d syntax in sleek recurrence expressions.

### CODE REVIEW

**Comment by ransome1** [comment]
@zerodat , thanks for another great contribution. Please give me some time to check it, as I'm a bit short on that right now ;)

**Comment by zerodat** [comment]
@ransome1 -- no problem, no rush.  Happy to help!

**Comment by ransome1** [comment]
@zerodat, ok I took a look at it and it seems to work perfectly fine, well done :1st_place_medal: 

One think I was asking myself is, if there is any need to implement the working days logic into the weekly, monthly or yearly recurrences as well?

@Moonbase59: The result of this PR looks like this
image

If you assume this is working well (I'll be building a pre-release for proper testing soon), does this meet the requirements of your feature request?

@nutnutwin: Is it ok, if I ask you to help out on the Chinese translations of "business day" and "business days"? If so, you can just post them here and I'll adapt them into the translation file.

**Comment by nutnutwin** [comment]
@ransome1 
Business Day = 工作日
Business Days = 工作日
There are no plural forms if you need to know(also for day, week, month, year ...)

**Comment by ransome1** [comment]
@nutnutwin, sorry I forgot there is also "each business day" :)

**Comment by zerodat** [comment]
@ransome1 thank you for merging!  To answer your question, I don't think there is anything else needed for weeks, months or years, as the business day handles any number of days (eg, like 50 or whatever) by properly stepping through them.  And I don't think that there is any similar concept of a "business month" or anything like that.

**Comment by nutnutwin** [comment]
> 
> 
> @nutnutwin, sorry I forgot there is also "each business day" :)

Right, "每个工作日" then
After you merged the new entry into json, I will do the Japanese translation(maybe start a new branch to avoid misunderstanding.

**Comment by ransome1** [comment]
Perfect, thanks a lot!

**Pull request merged**
