### PR TITLE
Allow sugar date formats in the edit todo field

### PR DESCRIPTION
**Pull request by weisserd**
This uses sugar for parsing due dates in the todo description.

Two things that should be mentioned:
* In the todo.txt file the date is written in standard format in order to not interfere with using more than one word for key:value extensions - see https://github.com/todotxt/todo.txt#additional-file-format-definitions
* Currently the enhancement just parses English date strings (e.g. tomorrow)

### CODE REVIEW

**Comment by weisserd** [comment]
This proposes a partial solution for #19

**Comment by ransome1** [comment]
@weisserd , lovely, thanks a lot for this PR. I'm a little short on time at the moment, but will look into it asap. I also got your mail and will reply soon.

**Comment by ransome1** [comment]
@weisserd thanks again for your PR. In general it seems to work quite well and it's fun to use. If this goes live we should think of a way to educate the user on this feature somehow. But that's another task. 

For now I found the following minor issues:
1. It doesn't work if you start the todo with a due date: `due:Tomorrow Name of the todo` (creates: `2021-06-08 due:Tomorrow Name of the todo`, should create: `2021-06-08 Name of the todo due:2021-06-09`
2. This unfortunately also affects the old function: `due:2021-07-01 Name of the todo` (creates: `2021-06-08 due:2021-07-01 Name of the todo`, should create: `2021-06-08 Name of the todo due:2021-07-01`)
3. It works well with a single word (`today`) and even two words (`next week`). As soon as there is a third word involved, it falls back to the first day of the current month, for instance `Name of the todo due:next week Thursday` creates `2021-06-08 Name of the todo  Thursday due:2021-06-15`. I'm not sure if this a very relevant use case, particulary if it expands the effort.

**Comment by weisserd** [comment]
@ransome1 Thanks for noticing the edge case with due at the beginning.

* I addressed the `due`@beginning issue with 0a54f6e - this should fix it
* For the multiple word detection of dates I simply switched from eager parsing (take always on word more up to the limit of 5) to parsing from 5 words down to one after the `due` keyword - c6a6bd2

**Comment by weisserd** [comment]
For the education and marketing a separate "help page" with a small screencast (GIF) might help. This could be reused for Twitter.

**Comment by weisserd** [comment]
And what I recognized of being helpful and maybe educating would be a "live synchronization" of the text entry with the advanced controls. E.g.
* If one enters `(A)` the priority is automatically updated
* If `due:tomorrow` is being entered the recognized date is populated in the date picker

However this would be an issue/wish of it s own.

**Pull request merged**
