### PR TITLE
Translation jp

### PR DESCRIPTION
**Pull request by nutnutwin**
as is promised in 
https://github.com/ransome1/sleek/issues/141
I did the Japanese translation

the Pulldown item should be ｢日本語｣

### CODE REVIEW

**Comment by ransome1** [comment]
@nutnutwin, again, thanks a lot! This is going to be released in 1.0.7

**Comment by ransome1** [comment]
@nutnutwin , if you like you can test the Japanese translations in the latest pre release: https://github.com/ransome1/sleek/releases/tag/v1.0.7

Thanks again for your support!

**Comment by nutnutwin** [comment]
@ransome1 
Two reports
1. add/edit window might need to be resized
20210622_Tue -093731

2. About Language Pick
Japanese Entry should be 
日本語
Currently it is ｢日本語｣
｢｣ is quotation, sorry

**Comment by ransome1** [comment]
@nutnutwin . I corrected 2.

But I don't understand 1. and 2. can you be more precise?

**Comment by ransome1** [comment]
Also: I found one missing translation: `"addTodo": "",`

Which in English is "Add a new todo"

**Comment by nutnutwin** [comment]
@ransome1 
For (1)
"期限なし" which means "No Due Date" is not shown properly, currently showing only "期限(half a word"
Also for "繰り返しなし" which is "No Repeat", is also half shown

For (3) I will provide more details if it occur

(4)  "Add a new todo"
"新しいタスクを作成"
should be fine

**Comment by ransome1** [comment]
(4) is added.

As for (1) I will download the language pack on Windows and try to reproduce it. Thanks for mentioning it.

**Comment by ransome1** [comment]
@nutnutwin I wasn't able yet to fix (1) yet (a little bit more tricky than I thought) but am now releasing the 1.0.7 as this is a minor issue. I didn't experience any JavaScript errors yet though.

The fix of (1) will be part of the next release then. If you have more details on (3) let me know and I'm happy to fix it.

**Comment by nutnutwin** [comment]
> @nutnutwin I wasn't able yet to fix (1) yet (a little bit more tricky than I thought) but am now releasing the 1.0.7 as this is a minor issue. I didn't experience any JavaScript errors yet though.
> 
> 
> 
> The fix of (1) will be part of the next release then. If you have more details on (3) let me know and I'm happy to fix it.

no Problem

**Pull request merged**
