### PR TITLE
feat: add time cost feat by  "Pomodoro Technique"

### PR DESCRIPTION
**Pull request by Jamlee**
1. show start and end date for todo.
image
2.  add pomodoro support. 
add `pm:` tag for record todo time cost. one poromodo is `25min`. https://en.wikipedia.org/wiki/Pomodoro_Technique
```
# for example
(B) 2023-03-11 buy somthing pm:3 +life @market
```
image

### CODE REVIEW

**Comment by Jamlee** [comment]
@ransome1 Hi

**Comment by ransome1** [comment]
Hi @Jamlee . Thanks for the PR! I don't know what Pomodore timer is, but I don't see a problem adding an extension to support it :) I'm going to checkout your commit and take a look at it.

As for the start and end date, I'm not sure if I can support your idea in the way you're proposing it. It adds a lot of characters to the line which are not necessarily self explanatory. Users will probably not understand what those dates mean and why some dates are being displayed with icons (due date, threshold date) and some are simply put at the end of the line. I suggest we should explore more ways of visualising these dates, so they are inline with the other dates and unambiguously make clear what they stand for.

**Comment by Jamlee** [comment]
@ransome1   i agree that view about  start and end date should improve.  🤔  i have no good idea to implement `self explanatory`

**Comment by ransome1** [comment]
@Jamlee I implemented your idea in the current developer preview of v2.0. Feel free to take a look at it. Unfortunately I wasn't able yet to find a free and open source tomato icon I liked :D

https://github.com/ransome1/sleek/releases/tag/v2.0.0-dev3

**Pull request closed without merging**
