### PR TITLE
feature/add removable-media plug

### PR DESCRIPTION
**Pull request by tssmits**
My todo.txt are stored on a mounted drive in /mnt/. By adding this plug, Sleek is able to get to that directory.

### CODE REVIEW

**Comment by ransome1** [comment]
@tssmits thanks a lot. It will be part of the next release.

**Comment by ransome1** [comment]
@tssmits this should have been released as part of 1.1.7 in Snap Store. Let me know if it works :)

**Comment by tssmits** [comment]
it seems the change didn't make it into 1.1.7, if i look at this file on line 34

<https://github.com/ransome1/sleek/blob/v1.1.7/snap/snapcraft.yaml#L34=>

**Comment by ransome1** [comment]
Oh, sorry. I think there went something wrong while merging on my side. I will add this right away and it will be part of 1.1.8.

**Comment by ransome1** [comment]
@tssmits I pushed this into the Edge channel of Snap. Could you please take a look at it, if this works on your side too?

**Comment by tssmits** [comment]
> @tssmits I pushed this into the Edge channel of Snap. Could you please take a look at it, if this works on your side too?

This works! :)

**Comment by ransome1** [comment]
Lovely, thanks for contributing this.

**Pull request merged**
