### PR TITLE
Add UI for threshold date

### PR DESCRIPTION
**Pull request by zemua**
Adding a clock button at the left of the due date button that sets the threshold instead.

### CODE REVIEW

**Comment by zemua** [comment]
This PR adds a button at the left side "Threshold Date"


Then each button sets the date separately


I ran into an issue that I'm not sure why was happening, after adding the Threshold date picker the date picker itself was keeping as selected in the calendar UI the last date chosen, even if it was regarding a different todo item. Both date pickers (due/threshold) keep this reference independently of each other.
I made a commit to fix this, basically it sets the picker date according to todo.due and todo.t when it is opened.
Also I had to add a null-catcher in the formatDate() function, otherwise when erasing the date it was throwing an error.

**Comment by ransome1** [comment]
Hi @zemua. Thanks a lot for your work on sleek! It's highly appreciated. So far I skipped the implementation of another date picker for the threshold date because I think (and this is just my opinion) not a lot of people have use cases to utilise it and therefor another major UI element would be added for all users but only adds an extra value for few.

I looked at your implementation and it works flawlessly especially after your recent push :) At this moment I might be having 3 issues with it: 1. I think it's positioned too promiment, 2. the use of the same icon is problematic and 3. if both dates are selected there is no more indication which date picker is for due and which is for threshold.

But I do have an idea and maybe we might work it out together. What if we somehow combine both the treshold and the due date into one picker? So we could have one input element in the modal windows and clicking on it would open one datepicker, that has maybe two tabs placed above the picker. Those tabs would be named "due date" and "threshold". And switching between those would of course preselect the appropriate due or threshold date.

I was messing a bit with the developer tools and this is just roughly what it could look like. Of course it would need more polish to fit the UI. 
Bildschirmfoto 2021-12-30 um 20 46 16

What are your thoughts on this?

**Comment by zemua** [comment]
Sounds good, though it means an extra click to switch the tab.
Personally I change around more the threshold date than the due date because I use it to manage which todos are shown in the list, together with the "don't show future tasks" feature. Maybe because I''m lazy, or bad organized, I keep pushing forward several todos each day when I don't want to work on them yet so they show up again tomorrow or in a few days.

Another option would be to, inside the options, allow choosing if the user wants this UI element or not.
If show = false then remove the DOM element.

**Comment by jdckr** [comment]
Would an additional keyboard shortcut make sense to open the desired tab already? In todotxt.net you have S and Ctrl+S when being in selection mode.
I have the same workflow as @zemua where I plan my days using the threshold dates. I normally don't use a gui to set the dates but the feature of todotxt.net where you can specify a day (e.g. t:fri, t:mon) to set threshold/due dates. In my fork I enhanced it to also be able to use relative dates (e.g. t:1d, t:2w, t:3m) like its done for topydo.

I don't want to spoil this PR but are these features you see in sleek as well?

**Comment by aubreyz** [comment]
I have to bump this one +10
Lots of people use threshold dates - they are not implemented that well
a) No date picker - so one needs to type in manually or use the due picker and then manually change the prefix
b) There is no indication in the task display that a threshold date is set at all! - should be the same as the due date display. 

This is a FANTASTIC app (by far the best windows implementation) but the absence of proper threshold date handling and saving of filter sets is keeping me on android simpletask

**Comment by zemua** [comment]
@aubreyz currently I'm using the one from my Pull Request, it has not any new update from sleek repo since I posted it here, but the threshold date works, which is a deal breaker for me.
I'm quite busy these days, but when I have some free time I might see how to include it with a different icon, and maybe an option to hide it from the UI if anyone just doesn't want to see it, in hopes that it could get included in the main sleek repo.

**Comment by aubreyz** [comment]
Can I suggest that a solution is to bring up the threshold dialog only with a keystroke shortcut (or to do something like hold down the shift key while pressing the date-due button) -- that way it will have no impact on people not using t:

Having an indication that there is a threshold date set in the display of each item is fairly vital though...

**Comment by zemua** [comment]
It seems neat. Personally I would open the date button by default in the threshold because it is just what I use more.
I'm also kind of missing an indicator of whether there is a threshold date already set.
Before I was thinking about leaving both buttons one behind the other like in my PR, then adding a switch in the options where you have the "invert sorting", "completed", etc... that said "show threshold button" or something like that. If switched it would show the button, otherwise it won't.

**Pull request merged**
