### PR TITLE
prevent multiple instances of the app

### PR DESCRIPTION
**Pull request by theperiscope**
- if the existing instance is minimized, window is restored and focused

### CODE REVIEW

**Comment by theperiscope** [comment]
Fixes https://github.com/ransome1/sleek/issues/257

**Comment by ransome1** [comment]
@theperiscope Thanks a lot. As soon as I have a bit more time on my hand I'm going to test and merge it.

**Comment by 9z0** [comment]
Goes without saying that this should be optional.

**Comment by theperiscope** [comment]
@9z0 I was thinking about that myself - if there are multiple instances, would it be possible to open same files in them? If yes, that might be a problem (from a refresh or write perspective) and a possible reason to not make optional. Also if multiple instances are allowed, tray/taskbar icons and may also be difficult to distinguish... Overall, to me, it felt that those instances provide decent reasoning for single-instance app, hence why I chose to log a bug and not a feature request. How do you see multiple instances working, differentiating and synchronizing between?

**Comment by 9z0** [comment]
@theperiscope The main point from the developer's perspective is that you are not aware of everyone's use case (not just cosmetic preferences, but actual usage scenarios), so not forcing a single way of doing things should be a goal as much as possible.

In my particular case, I used tabs until I noticed that [switching between them clears any active filter/search](../issues/254). So I have to use separate instances/windows until that issue is fixed.

Otherwise, I might, for example, use two instances with different themes so that I don't confuse two similar todo.txt files being actively edited. Or maybe I would like to use the system window preview feature (like on Alt+tab or hover on taskbar) which is not possible with tabs. Or maybe because it is faster than waiting for sleek to build the table on each switch etc... etc...

**Comment by zerodat** [comment]
I agree with @9z0 that there should be an option to open a new instance, perhaps with a command-line option flag (like `--new-instance`).  This is useful to view multiple files in separate instances, and also for testing and development purposes, so certainly worth adding the option.

**Comment by ransome1** [comment]
I'm with @theperiscope on this topic. I don't recall a single app that let me open itself in several instances. Having sleek open in several instances sounds like an edge case. 

@9z0 is using several instances only because he has a use case sleek is not able to deliver on yet. But that should not stand in the way of fixing things that need to be fixed.

**Comment by ransome1** [comment]
@zerodat implementing an option in the config file or as a command line option shouldn't be a big problem. I'll see if I can add it the next release.

**Comment by zerodat** [comment]
Thanks, @ransome1.  It will be useful to have the option.  Just FYI, firefox is an example of an app that can be opened in multiple instances using `--new-instance`.

**Comment by ransome1** [comment]
@zerodat @9z0 for the upcoming release of 1.1.4 (most likely today) the single instance behavior will set in. I added an environment variable `SLEEK_MULTIPLE_INSTANCES` that can be set to `true`, which will then force sleek to open multiple instances.

**Comment by ransome1** [comment]
@theperiscope Did you check it and can we close here?

**Comment by theperiscope** [comment]
@ransome1 I tested it over the weekend - works very well on Windows 10 Pro, I'll try later today on my old MacBook Pro.

As more of a wish, rather than an issue, I'd like in single-instance mode the window to come to front/focus if minimized to tray or in the background - I frequently start things from the Start Menu rather than the tray icon and that will increase usability even further for me... my original PR included an attempt to do that but admittedly I did not test it on all platforms at the time.

**Comment by ransome1** [comment]
> As more of a wish, rather than an issue, I'd like in single-instance mode the window to come to front/focus if minimized to tray or in the background

I'm not 100% sure if I understand this. You mean if sleek is in tray and in background and you use tabbing to select it, you would like sleek to reappear?

**Comment by theperiscope** [comment]
@ransome1 not tabbing - rather starting the app twice. Let me try to provide an example:

1. start sleek (single-instance mode), and close window (result: icon in tray)
2. start sleek again from start menu

current result: no window appears (because sleek in minimized to tray)
desired result: restore window 

I reason that user (me) took an intentional action (to start the app) and because of that the app window should appear - whether or not app was started previously is secondary (Windows for example hides some icons, so user may have forgotten they started sleek).

**Comment by ransome1** [comment]
> @ransome1 not tabbing - rather starting the app twice. Let me try to provide an example:
> 
> 1. start sleek (single-instance mode), and close window (result: icon in tray)
> 2. start sleek again from start menu
> 
> current result: no window appears (because sleek in minimized to tray) desired result: restore window
> 
> I reason that user (me) took an intentional action (to start the app) and because of that the app window should appear - whether or not app was started previously is secondary (Windows for example hides some icons, so user may have forgotten they started sleek).

Ah ok, got it. Let's see what we can do :)

**Pull request closed without merging**
