### PR TITLE
Support strict recurrence using optional plus-sign syntax

### PR DESCRIPTION
**Pull request by zerodat**
Recently the default recurrence behavior in sleek was changed to the "non-strict" behavior, where the base date for recurrences like "rec:2w" is today's date (the completion date of the original task).   This is consistent with recurrence behavior in other todo.txt tools.

This PR adds the recurrence syntax "rec:+2w" to invoke the "strict" recurrence behavior where the base date for the recurrence is the previous due date.  This additional syntax is also consistent with other todo.txt tools (like [simpletask for android](https://github.com/mpcjanssen/simpletask-android) and [topydo](https://github.com/topydo/topydo)).  See also [recurrence spec](https://cdn.rawgit.com/bram85/topydo/master/docs/index.html#Recurrence). It is good to have both recurrence methods, because some tasks ("wash the windows") are naturally non-strict, and others ("pay this months rent") are naturally strict.  For now, there is no new UI for the "rec:+2w" syntax.  People who want to use the new syntax would have to add the plus directly in the text field for the task.  That seems fine to me since it will likely be more sophisticated users who would use the strict recurrence feature.  I'd be happy to help build some UI for this later if people feel that it is necessary.

The PR doesn't change the existing non-strict behavior when you use the default syntax.  

The PR is safe to merge right now and I'd prefer to get it into sleek as soon as possible, but there is one limitation in using it until the recently merged upstream fix for [Issue #29 · jmhobbs/jsTodoTxt](https://github.com/jmhobbs/jsTodoTxt/issues/29) is released. Until this is fixed, if you have a project in a task, any other plus signs in the task will be deleted including ones in rec: values.  If you don't have a project, it will work fine.  So for example, you can test this PR using tasks like `pay this months rent rec:+1m` but not `pay this months rent rec:+1m +bills`.  Since the new syntax is optional, it would be great to get this into sleek now in anticipation of the jsTodoTxt fix being released soon.

### CODE REVIEW

**Comment by ransome1** [comment]
Thanks a lot @zerodat.

As a workaround I copied your changes to jsTodoTxt.js from https://github.com/jmhobbs/jsTodoTxt/pull/30 and it's working well for `2021-06-01 test rec:+2d due:2021-06-03`

It's not working though if you leave the number out as in: `2021-06-01 test rec:+d due:2021-06-03`

**Comment by zerodat** [comment]
Ah, OK.  I'll take a look at fixing that right now.  Sorry for not noticing it.

**Comment by zerodat** [comment]
Hi, @ransome1.  I have pushed an additional commit which should fix the problem that you found.  Thanks!

**Comment by ransome1** [comment]
Works like a charm :1st_place_medal: 

Let's hope jsTodoTxt releases the PR in a NPM package update soon so we can make this part of 1.0.6. Thanks a lot for your work on sleek, it's highly appreciated.

**Comment by ransome1** [comment]
@zerodat , I think I might have found a little glitch. If you create a todo with strict recurrence but no due date (`2021-06-02 test rec:+d`), the getRecurrenceDate function will break as the `due` variable will remain `undefined`.

For non-strict you added this exception
```
  if (!recSplit.plus) {
    // no plus in recurrence expression, so do the default "non-strict" recurrence.
    // (Otherwise we will use the previous due date, for strict recurrence.)
    due = new Date();  // use today's date as base for recurrence
  }
```

I think this could be fixed, if we change this to
```
  if (!recSplit.plus || !due) {
    // no plus in recurrence expression, so do the default "non-strict" recurrence.
    // (Otherwise we will use the previous due date, for strict recurrence.)
    due = new Date();  // use today's date as base for recurrence
  }
```
What do you think?

**Comment by zerodat** [comment]
@ransome1, I think you're right.  Sorry I missed that. I think the case of no due date used to be handled by the code in `generateRecurrence` but that  code has been simplified.  The fix that you are suggesting seems like the correct one.  Thanks for fixing it!  Let me know if you need me to do anything about it.

**Comment by ransome1** [comment]
Hi @zerodat, I updated the sleek wiki on recurrences: https://github.com/ransome1/sleek/wiki/Recurring-todos

It's not urgent but if you find the time, I would appreciate it, if you could read it and let me know if this is also your understanding on how recurrences are now implemented in sleek.

**Comment by ransome1** [comment]
@zerodat I invited you to become a collaborator on sleek

**Comment by zerodat** [comment]
Thank you, @ransome1!

**Pull request merged**
