### PR TITLE
added support for relative due and threshold date

### PR DESCRIPTION
**Pull request by jdckr**
This PR adds support for relative dates to set due date or threshold. This is inspired by topydo.
Syntax is t:1d or due:2w. Supported is [d]ays, [w]eeks and [m]onths.

### CODE REVIEW

**Comment by zerodat** [comment]
Hi, @jdckr.  Just wondering how this would work if it is Jan 31 and you type `due:1m`?  Would it be useful to call the `addIntervalToDate` function from `recurrences.mjs`?

**Comment by jdckr** [comment]
It just adds 4 weeks: https://onecompiler.com/javascript/3xsremkd4 
What did you expect?
I didn't know about the other function. It seems to do s.th. similar. Though haven't checked it in detail yet. When is that function used?

**Comment by ransome1** [comment]
@jdckr thanks archer ;)

@zerodat do you see any obstacles with this implementation?

**Comment by zerodat** [comment]
I think there is a bug.  Line 97 of todotxtExtensions.mjs:

```
date.setMonth(date.getMonth() + 1);
```
should be
```
date.setMonth(date.getMonth() + increment);
```
I believe.

**Comment by zerodat** [comment]
@jdckr , in addition to that bug, the original point I was making is this:  The code doesn't add 4 weeks -- it adds 1 month and the length of a month varies.  In the example I gave of adding 1m to Jan 31, the result will be March 3, because the setMonth() method changes Feb 31 into March 3.  Try your code https://onecompiler.com/javascript/3xsremkd4 and you will see that is the result.

You said you were inspired by topydo, but topydo works differently.  In topydo, if it is Jan 31, `topydo add "this task due:1m"` will give you a due date of Feb 28, not March 3.  I suggested that you call `addIntervalToDate` from sleek's `recurrences.mjs` because it works the same way as topydo.  It is used for the date recurrences in sleek, and so your result would be consistent with existing sleek behavior and with topydo.  You should be able to do something like:
```
function resolveRelativeDate(relativeDate) {
    var unit = relativeDate.slice(-1);
    var increment = parseInt(relativeDate.slice(0, -1));
    return addIntervalToDate(new Date(), increment, unit);
}
```
Let me know if this isn't clear.  Thanks.

**Comment by jdckr** [comment]
@zerodat good catch for the hard coded values. How can I add UnitTests for such a function? Can you give me some hints. Checked the files in test folder but couldn't get it run.

I haven't tried the corner cases and also never had those in topydo. I agree for the corner cases that this might be useful to rather set it to the end of the next month instead of jumping at the beginning of the next. But in general it should just increment the month. This is also what topydo is doing:
image
I tried to use your code but there it results in 2022-03-11 if I do it for today (2022-02-12).

So what would be the expectation? Add x month(s) and clamp to the end of the month if it exceeds the last possible date of a month? I assume you don't want to use the length of the current month for all calculations?

**Comment by zerodat** [comment]
@jdckr that is interesting.  I think that the problem might be due to current time of day and timezone.   The UTC time might be a different day than your local time, so the result is correct for UTC, but wrong for your local time.

Please try this code instead, which make sure that `today` contains the local date with zeroed out time.

```
function resolveRelativeDate(relativeDate) {
    var now = new Date();
    var today = new Date(now.getFullYear(), now.getMonth(), now.getDate(), 0, 0, 0, 0);
    var unit = relativeDate.slice(-1);
    var increment = parseInt(relativeDate.slice(0, -1));
    return addIntervalToDate(today, increment, unit);
}
```
I think that should work without timezone-related issues.  Topydo actually does something like `addIntervalToDate`, but that code is in Python, not Javascript, so the behavior of the built-in date objects is a little bit different.  In topydo it is `RelativeDate._add_months`, in case you want to go look at it.

**Comment by jdckr** [comment]
@ransome1 and how to execute them?

**Comment by ransome1** [comment]
If you want to start all tests I've written so far simply do `yarn playwright test`

If you only want to start a specific one do `yarn playwright test -g "Due date picker"`

**Comment by jdckr** [comment]
@zerodat I tried the new proposed code but still the same issue, the date is off by 1 day. I have pushed this to a branch so you can try it yourself if you are interested: https://github.com/jdckr/sleek/tree/feature/relative-due-and-threhsold-date-debug
I wanted to provide some UnitTests but I am lost in import vs. require hell. I am new to JS so this might take some while for me to get going :-|

**Comment by jdckr** [comment]
It fails when converting the date to a string

image

**Comment by zerodat** [comment]
Thank you, @jdckr!  Although using `toISOString()` gets you the desired format,I think it also changes the date when converting your local time into UTC.  It seems that I'm not able to reproduce the problem because my timezone is -8, while yours is +1.

To avoid the problem, maybe you could use an alternate method to get the desired format.  I couldn't find any built-in Javascript formatting to get the local time in YYYY-MM-DD format, so I wrote this little function for you to use:
```
function localDateString(d) {
  function zeropad(value, len) {
    var s = value.toString();
    while (s.length < len) {
      s = "0" + s;
    }
    return s;
  }
  return d.getFullYear().toString() + "-" + zeropad(d.getMonth()+1, 2) + "-" + zeropad(d.getDate(), 2);
}
```
Then you could use `var debug = localDateString(thresholdDate);` instead of using `toISOString()`.

**Comment by ransome1** [comment]
@jdckr  @zerodat if you're trying to convert a date object into a todo.txt compatible date format (xxxx-xx-xx), you should use the `formatDate()` function, that is already available in the `helper.mjs` module.

https://github.com/ransome1/sleek/blob/e3522cb75a35cd5249d6133d861901b2e3edec02/src/js/helper.mjs#L326

**Comment by zerodat** [comment]
Yes, thanks @ransome1.  That's equivalent to the `localDateString` from my message, and it should work nicely for @jdckr's code.

**Comment by zerodat** [comment]
@jdckr don't you still need to change to formatDate in line 33 of todotxtExtensions.mjs, ie:

```
return [dueDate, line.replace(relativeDateRegEx, ''), dueDate.toISOString().split('T')[0]];
```
should be
```
return [dueDate, line.replace(relativeDateRegEx, ''), formatDate(dueDate)];
```

Also you could loosen up your regex so that it matches all of the available units (d, b, w, m, y) with or without a count:
```
var relativeDateRegEx = /due:(\d*[dbwmy])/;
```
in lines 27 and 65.  At line 90 in resolveRelativeDate, you should then test to see whether the relativeDate string is longer than 1, and if it isn't, default the increment to 1.

**Comment by jdckr** [comment]
> 



> @jdckr don't you still need to change to formatDate in line 33 of todotxtExtensions.mjs, ie:
> 
> ```
> return [dueDate, line.replace(relativeDateRegEx, ''), dueDate.toISOString().split('T')[0]];
> ```
> 
> should be
> 
> ```
> return [dueDate, line.replace(relativeDateRegEx, ''), formatDate(dueDate)];
> ```

Fixed :|



> Also you could loosen up your regex so that it matches all of the available units (d, b, w, m, y) with or without a count:
> 
> ```
> var relativeDateRegEx = /due:(\d*[dbwmy])/;
> ```
> 
> in lines 27 and 65. At line 90 in resolveRelativeDate, you should then test to see whether the relativeDate string is longer than 1, and if it isn't, default the increment to 1.

Nothing I personally need so far. I use this feature heavily in my daily workflow with todotxt.net. 
What I still miss is to specify day names (as it works for due), sorting by threshold (already playing around with it), changing several items at once, saved filters (#106 :-( ) ... just using sleek to see how much effort it is to change it or my workflow or if I just stay with todotxt.net.

**Comment by ransome1** [comment]
@jdckr sorry for the late merge. I gave it some testing already and I think it works fine. I will release it as part of 1.2.0 :)

@zerodat thanks for supporting here.

**Comment by ransome1** [comment]
@jdckr in case you want to see your enhancement in action, it is part of the latest pre-release: https://github.com/ransome1/sleek/releases/tag/v1.2.0-rc.2

Let me know, if anything doesn't work as intended.

**Pull request merged**
