### PR TITLE
Translation cj

### PR DESCRIPTION
**Pull request by nutnutwin**
@ransome1 
Made some fixes I noticed on my previous translation

some still does not sound very native, will follow up on this

some questions
- cannot find 
  ｢  "helpTabKeyboardTR8TD1": "Toggle filter drawer",｣ anywhere on the UI
- as for
  ｢  "of": "of",｣ I left it as it is
  reason: A of B = B 的 A in Chinese, which will be mistaken if only translate the word "if"
- BTW, I cannot find the json Entry for "Zoom"

### CODE REVIEW

**Comment by nutnutwin** [comment]
↑Sorry seems I cannot resolve the conflicts...

**Comment by nutnutwin** [comment]
BTW, I cannot find the json Entry for "Zoom"

**Comment by ransome1** [comment]
@nutnutwin, `helpTabKeyboardTR8TD1` is part of the shortcut table in help menu.

But I just realized that I left a couple of english terms hard coded without any translations. Shame on me :/ 

I will add those hard coded terms to the translation file and would like to ask you for translations when the time comes, if that is ok.

**Comment by nutnutwin** [comment]
no Problem at all

**Comment by nutnutwin** [comment]
@ransome1 
no problem, think I just replied to the other thread #141

**Pull request merged**
