### PR TITLE
WIP: UUID tag feature

### PR DESCRIPTION
**Pull request by chaotika**
I made some changes that adds special handling for UUID tags similar to how it is solved in Simpletask.

This is still a WIP:

- [x] hides the uuid tag in the table when it is in fact an uuid 
- [x]  shows an info symbol which displays the uuid.
- [ ] Hide UUID from the edit form but add an UUID edit button
- [ ] Option to automatically add UUID tag to all tasks

### CODE REVIEW

**Comment by ransome1** [comment]
Hi @chaotika thanks for contributing this. Unfortunately I'm afk until end of May and can't take a look at this at the moment. I will do this once I'm back. Please feel free to keep on fine tuning it meanwhile. Also if it contains graphical adjustments, please check if it works on bright and dark mode as well as compact mode and when sleeks window is narrowed down.

As far as I can tell this adds a support to identify a tag named uuid and displays it in a specifically designed shape. Is that correct?

I never heard of this but if there is a good use case for some users I'll support this.

I saw you added it to the readme which is a good idea in general. My plan though is to reduce the readme on GitHub to the bare minimum so the majority of users can decide if sleek is for them or not. I was thinking about putting smaller and very specific features to a complete list in the sleek wiki.

**Comment by chaotika** [comment]
> Hi @chaotika thanks for contributing this. Unfortunately I'm afk until end of May and can't take a look at this at the moment. I will do this once I'm back. Please feel free to keep on fine tuning it meanwhile. Also if it contains graphical adjustments, please check if it works on bright and dark mode as well as compact mode and when sleeks window is narrowed down.

Thank you for your program, I really like it.

I did not change much of the CSS, but there is a little problem with the display of long tags, I will post some screenshots soon. Maybe you have some idea how to fix those. 

> As far as I can tell this adds a support to identify a tag named uuid and displays it in a specifically designed shape. Is that correct?

Yes, exactly.

> I never heard of this but if there is a good use case for some users I'll support this.

The Simpletask app has this feature too. You can automatically add UUIDs to the tasks and they ae hidden from the task list.
Screenshot_20220426-225541

The use case for this is to add a primary key to every task so that you can reference the tasks reliably. With that you can sync it with a database or track changes for example. I use it for time tracking individual tasks with the UUID so the time is still recorded recorded to the task if I change something. 

> I saw you added it to the readme which is a good idea in general. My plan though is to reduce the readme on GitHub to the bare minimum so the majority of users can decide if sleek is for them or not. I was thinking about putting smaller and very specific features to a complete list in the sleek wiki.

**Comment by ransome1** [comment]
Ok I see. This makes sense. Do you think we should add an option and let sleek add a random uuid to each task of its enabled?

**Comment by chaotika** [comment]
Yes, this is the next thing i want to implement.

**Comment by ransome1** [comment]
Hi @chaotika . Can I ask if you were able to finish this up?

**Pull request closed without merging**
