### PR TITLE
Add French translation

### PR DESCRIPTION
**Pull request by yannicka**

### CODE REVIEW

**Review by ransome1 — APPROVED** [review]
Hi @yannicka , thanks a lot :)

I'll merge it and build the the 0.7.2.

Really appreciate your support.

**Comment by ransome1** [comment]
https://github.com/ransome1/sleek/releases/tag/v0.7.2

**Comment by ransome1** [comment]
Hi @yannicka . Can I ask you for another quick translation? There will be an archiving function in the settings modal in 0.8.0. I can only provide translations for DE and EN. If you'll find a little time, please feel free so translate the three new lines in the translations.json:
- "settingsTabSettingsArchive": "Archive todos",
- "settingsTabSettingsArchiveBody": "Completed todos will be removed from the current todo.txt file and inserted into a done.txt file. If this file doesn't already exist in the current directory, it will be created.",
- "settingsTabSettingsArchiveButton": "Archive"

**Comment by yannicka** [comment]
Sure, no problem: #23

**Pull request merged**
